version: "3.9"

services:
  server:
    restart: always
    image:  'nginx:stable-alpine'
    ports:
     - 8888:80
     - 443:443
    volumes :
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
     - ./src:/var/www/html:delegated
     - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
  mysql: 
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=matryxforsnipetechstandalone
      - MYSQL_USER=matryx_docker
      - MYSQL_PASSWORD=PogiAko2023 # this should live in a env var
      - MYSQL_ROOT_PASSWORD=PogiAko2023
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./src/db:/docker-entrypoint-initdb.d"
    ports:
    - 3306:3306
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
